#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install languages
##?
##? Usage:
##?    install
##?

docs::parse "$@"

 if ! platform::command_exists go; then
  if platform::is_macos; then
    brew install go
  else
    if platform::command_exists apt; then
      sudo apt -y install golang-go
    elif platform::command_exists dnf; then
      sudo dnf -y install golang
    elif platform::command_exists yum; then
      yes | sudo yum install golang
    elif platform::command_exists pacman; then
      sudo pacman -S --noconfirm go
    fi
  fi

  if platform::command_exists docker; then
    log::success "Golang installed"
  else
    log::error "Golang installation failed"
  fi
else
  output::write "✔ Golang installed"
fi
