#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

red='\033[0;31m'
green='\033[0;32m'
purple='\033[0;35m'
normal='\033[0m'

_w() {
  local -r text="${1:-}"
  echo -e "$text"
}
_a() { _w " > $1"; }
_e() { _a "${red}$1${normal}"; }
_s() { _a "${green}$1${normal}"; }
_q() { read -rp "🤔 $1: " "$2"; }

current_timestamp() { date +%s; }

command_exists() {
  type $1 >/dev/null 2>&1
}

_w "┌───────────────────────────────────────┐"
_w "│ 🚀 Welcome to the ${green}dotfiles${normal} installer! │"
_w "└───────────────────────────────────────┘"
_w

if ! command_exists git; then
  _e "git not installed, trying to install"

  if command_exists apt; then
    _a "Installing using apt"
    sudo apt -y install git 2>&1 | _log "Installing git"
  elif command_exists dnf; then
    _a "Installing using dnf"
    sudo dnf -y install git 2>&1 | _log "Installing git"
  elif command_exists yum; then
    _a "Installing using yum"
    yes | sudo yum install git 2>&1 | _log "Installing git"
  elif command_exists brew; then
    _a "Installing using brew"
    yes | brew install git 2>&1 | _log "Installing git"
  elif command_exists pacman; then
    _a "Installing using pacman"
    sudo pacman -S --noconfirm git 2>&1 | _log "Installing git"
  else
    case "$OSTYPE" in
    darwin*)
      _a "Checking if Command Line Tools are installed 🕵️‍♂️"

      xcode-select --install 2>&1 | grep installed >/dev/null
      if [[ $? ]]; then
        _a "Installing Command Line Tools 📺"
        xcode-select --install
        _q "Press a key after command line tools has finished to continue...👇" "CLT_INSTALLED"
      fi
      ;;
    *)
      _e "Could not install git, no package provider found"
      exit 1
      ;;
    esac
  fi
fi

export DOTFILES_PATH="$HOME/.dotfiles"
_w "👉  Cloning into: '$DOTFILES_PATH'"
_w


git clone --depth 1 git@github.com:franciscoruizar/dotfiles.git "$DOTFILES_PATH"


_w "Installing tools 🧰"
source $DOTFILES_PATH/tools/init.sh
_s "Ready ✔️"

_w

_w "Installing languages 📱"
source $DOTFILES_PATH/langs/init.sh
_s "Ready ✔️"

_w "Configuring dotfiles 🗃️"
_s "Ready ✔️"