#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Exec Bash of Docker Container
#?? 1.0.0
##?
##? Usage:
##?   exec <container>
docs::parse "$@"

docker exec -it $1 /bin/bash