#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install docker
##?
##? Usage:
##?    install
##?

if ! platform::command_exists docker; then
  sudo bash <(curl -s https://get.docker.com/) 2>&1 | log::append "Installing docker"
  sudo groupadd docker | log::append "Group add docker"
  sudo usermod -aG docker $USER  | log::append "Usermod docker user"
  newgrp docker
  
  if platform::command_exists docker; then
    log::success "Docker installed"
    output::write "✅ Docker installed"
  else
    log::error "Docker installation failed"
    output::write "❌ Docker installation failed"
  fi

  else
    output::write "✔ Docker installed"
fi

