#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install docker
##?
##? Usage:
##?    install
##?

if ! platform::command_exists docker; then
  log::append "Installing docker"
  bash <(curl -s https://get.docker.com/)
  
  if platform::command_exists docker; then
    log::success "Docker installed"
    output::write "✅ Docker installed"
  else
    log::error "Docker installation failed"
    output::write "❌ Docker installation failed"
  fi

  else
    output::write "✔ Docker installed"
fi

