#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List docker containers
#?? 1.0.0
##?
##? Usage:
##?   list-containers
docs::parse "$@"

containers=$(docker ps -a | awk '{if (NR!=1) print $1 ": " $(NF) " - " $2 " - " $7 " " $8 " " $9 }')

echo "👇 Containers 👇"

printf '%s ' "${containers[@]}"
printf '\n'