#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List docker containers
#?? 1.0.0
##?
##? Usage:
##?   list-containers
##?   list-containers -a
docs::parse "$@"

if getopts "a" arg; then
  containers=$(docker ps -a | awk '{if (NR!=1) print $1 ": " $(NF)}')

  echo "👇 Containers 👇"
  echo $containers
else
  containers=$(docker ps | awk '{if (NR!=1) print $1 ": " $(NF)}')

  echo "👇 Containers 👇"
  echo $containers
fi
