#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List docker containers
#?? 1.0.0
##?
##? Usage:
##?   list_containers
docs::parse "$@"

containers=$(docker ps -a | awk '{if (NR!=1) print $1 ": " $(NF)}')

echo "👇 Containers 👇"
echo $containers