#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List docker containers
##?
##? Usage:
##?    list
##?

docs::parse "$@"

containers=$(docker ps | awk '{if (NR!=1) print $1 ": " $(NF)}')

output::write "👇 Containers 👇"
output::write $containers
