#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Apply all symlinks
##?
##? Usage:
##?    apply
##?

docs::parse "$@"

source "$DOTFILES_PATH/symlinks/links.sh"

log::success "Done!"
