#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Apply all symlinks
##?
##? Usage:
##?    disable
##?
docs::parse "$@"

source "$DOTFILES_PATH/symlinks/unlinks.sh"

log::success "Done!"
