#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install and setup VsCode
#?? 1.0.0
##?
##? Usage:
##?   install
docs::parse "$@"

"$DOTFILES_PATH/bin/dot" vscode install

"$DOTFILES_PATH/bin/dot" vscode extensions

"$DOTFILES_PATH/bin/dot" vscode setup