#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/symlinks/utils.sh"

##? Install DOTFILES and setup dotfiles
##?
##? Usage:
##?    install_all
docs::parse "$@"

"$DOTFILES_PATH/bin/dot" vscode install
"$DOTFILES_PATH/bin/dot" vscode install_extensions

if platform::is_macos; then
  ensure_if_exists_file ~/Library/Application\ Support/Code/User/settings.json
  ln -s $DOTFILES_PATH/editors/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
elif platform::is_macos; then
  ensure_if_exists_file ~/.config/Code/User/settings.json
  ln -s $DOTFILES_PATH/editors/vscode/settings.json ~/.config/Code/User/settings.json
elif platform::is_wsl; then
  ensure_if_exists_file $WINHOME/AppData/Roaming/Code/User/settings.json
  ln -s $DOTFILES_PATH/editors/vscode/settings.json $WINHOME/AppData/Roaming/Code/User/settings.json
fi

