#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/vscode/utils.sh"

##? Install and setup VsCode
#?? 1.0.0
##?
##? Usage:
##?   install
docs::parse "$@"

install_vscode
install_vscode_extensions
setup_vscode_settings_file