#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install VsCode
#?? 1.0.0
##?
##? Usage:
##?   install
docs::parse "$@"

if ! platform::command_exists code; then
    if platform::command_exists apt; then
      output::answer "Installing VsCode using apt"
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
      sudo sh -c 'echo "deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
      sudo apt update
      sudo apt -y install code
    elif platform::command_exists dnf; then
      output::answer "Installing VsCode using dnf"
      sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
      sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
      dnf check-update
      sudo dnf install code
    elif platform::command_exists yum; then
      output::answer "Installing VsCode using yum"
      sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
      sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
      yum check-update
      sudo yum install code
    elif platform::command_exists brew; then
      output::answer "Installing VsCode using brew"
      yes | brew install --cask visual-studio-code
    elif platform::command_exists pacman; then
      output::answer "Installing VsCode using pacman"
      sudo yaourt -S visual-studio-code
    fi
fi

if platform::command_exists code; then
   echo "✅ installed!"
fi
