#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install VsCode extensions
#?? 1.0.0
##?
##? Usage:
##?   setup
docs::parse "$@"

source "$DOTFILES_PATH/symlinks/utils.sh"

if platform::is_macos; then
  ensure_if_exists_file ~/Library/Application\ Support/Code/User/settings.json
  ln -s $DOTFILES_PATH/editors/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
elif platform::is_macos; then
  ensure_if_exists_file ~/.config/Code/User/settings.json
  ln -s $DOTFILES_PATH/editors/vscode/settings.json ~/.config/Code/User/settings.json
elif platform::is_wsl; then
  ensure_if_exists_file $WINHOME/AppData/Roaming/Code/User/settings.json
  ln -s $DOTFILES_PATH/editors/vscode/settings.json $WINHOME/AppData/Roaming/Code/User/settings.json
fi
