#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

current_timestamp() { date +%s; }

ensure_if_exists_file(){
  if [ -f $1 ]; then
      mv $1 $1.$(current_timestamp).back
  fi
}

##? Setup VsCode configs
#?? 1.0.0
##?
##? Usage:
##?   setup
docs::parse "$@"

if platform::is_macos; then
    ensure_if_exists_file ~/Library/Application\ Support/Code/User/settings.json
    ln -s $DOTFILES_PATH/editors/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
elif platform::is_macos; then
    ensure_if_exists_file ~/.config/Code/User/settings.json
    ln -s $DOTFILES_PATH/editors/vscode/settings.json ~/.config/Code/User/settings.json
elif platform::is_wsl; then
    ensure_if_exists_file $WINHOME/AppData/Roaming/Code/User/settings.json
    ln -s $DOTFILES_PATH/editors/vscode/settings.json $WINHOME/AppData/Roaming/Code/User/settings.json
fi