#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show all changed files to default branch
##?
##? Usage:
##?   changed-filed
docs::parse "$@"

default_branch = $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

git diff --name-only ${default_branch}
