#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Add all files and then a commit
#?? 1.0.0
##?
##? Usage:
##?   commit
##?   commit <message>

echo $1
echo $#

git add -A

if [ $# -ge 1 ] && [ -n "$1" ]; then
  git commit -m"$1"
else
  git commit
fi
