#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List contributors with number of commits
##?
##? Usage:
##?   contributors

git shortlog --summary --numbered
