#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Delete multiple branches based on a specified pattern
##?
##? Usage:
##?   delete <branch_pattern>
docs::parse "$@"

git branch | grep "$1" | xargs git branch -d -D

echo "Delete all branch's 🤘"
