#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Delete multiple branches based on a specified pattern
##?
##? Usage:
##?   delete <branch_pattern>
##?   delete fix/
##?   delete feat/
##?   delete release/
##?   delete migration/
docs::parse "$@"

git branch | grep "$1" | xargs git branch -D

echo "Delete all branch's 🤘"