#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Switch to personal or work mail
##?
##? Usage:
##?   mail <personal>
##?   mail <work>
docs::parse "$@"

if [ "$1" == "personal" ]; then
	git config --global user.email "franciscoruizlezcano@gmail.com"
else
	git config --global user.email "francisco.ruiz@mercadolibre.com"
fi

echo "Mail changed 🤘"