#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Create migration branch
##?
##? Usage:
##?   migration <branch_name>
docs::parse "$@"

git checkout master
git pull origin master
git checkout -b "migration/$1"

fury migration init

echo "Migration created 🤘"