#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install languages
##?
##? Usage:
##?    install
##?

languages:install_java() {
  if ! platform::command_exists java; then
    if platform::is_macos; then
      "$DOTFILES_PATH/bin/dot" package add openjdk
    elif platform::is_macos_arm; then
      "$DOTFILES_PATH/bin/dot" package add openjdk
    else
      "$DOTFILES_PATH/bin/dot" package add default-jdk
      "$DOTFILES_PATH/bin/dot" package add default-jre
    fi
  else
    output::write "✔ Java installed"
  fi
}


languages:install_golang() {
  if platform::is_macos; then
    "$DOTFILES_PATH/bin/dot" package add go
  elif platform::is_macos_arm; then
    "$DOTFILES_PATH/bin/dot" package add go
  else
    if platform::command_exists apt; then
      "$DOTFILES_PATH/bin/dot" package add golang-go
    elif platform::command_exists dnf; then
      "$DOTFILES_PATH/bin/dot" package add golang
    elif platform::command_exists yum; then
      "$DOTFILES_PATH/bin/dot" package add golang
    elif platform::command_exists pacman; then
      "$DOTFILES_PATH/bin/dot" package add go
    fi
  fi
}


languages:install_java
languages:install_golang