#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? DDD
#?? 1.0.0
##?
##? Usage:
##?    ddd
##?    ddd <path>
docs::parse "$@"

CURRENT_PATH="$PWD"

if [ $# -ge 1 ] && [ -n "$1" ]; then
  CURRENT_PATH="$1"
  CURRENT_PATH="$1"
  CURRENT_PATH="$1"
fi

mkdir -p "$CURRENT_PATH/application"
mkdir -p "$CURRENT_PATH/domain"
mkdir -p "$CURRENT_PATH/infrastructure"

echo "😬 Dooone!"
