#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Kill process port
#?? 1.0.0
##?
##? Usage:
##?   kill_port <to_kill>
docs::parse "$@"

kill $(lsof -t -i:$1)

echo 'done!'