#!/usr/bin/env bash
set -eo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Downloads a video or audio of youtube video in the current directory
##?
##? Usage:
##?   youtube <url>
##?   youtube mp3 <url>

if [ $2 == "mp3" ]; then
  youtube-dl -x --audio-format mp3 "$1"
else
  youtube-dl --format mp4 "$1"
fi

echo "done!"