#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/editors/utils/files.sh"

##? Install VIM and settings
##?
##? Usage:
##?   vim setup
docs::parse "$@"

case $1 in
"setup")
    output::answer "⚙️ Setup VIM settings"
    ensure_if_exists_file ~/.vimrc
    ln -s $DOTFILES_PATH/editors/.vimrc ~/.vimrc
    output::write "✅ Done"
  ;;
*)
  exit 1
  ;;
esac