#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install VIM and settings
##?
##? Usage:
##?   vim all
##?   vim install
##?   vim setup
docs::parse "$@"

case $1 in
"all")
    "$DOTFILES_PATH/bin/dot" editors vim install
    "$DOTFILES_PATH/bin/dot" editors vim setup
  ;;
"install")
    output::answer "Installing VIM"
    if ! platform:command_exists vim; then
        "$DOTFILES_PATH/bin/dot" package add vim
    fi

    if platform:command_exists vim; then
        "$DOTFILES_PATH/bin/dot" package add vim
        output::write "✅ Done"
    else
        output::write "Opps! VIM not installed"
    fi
  ;;
"setup")
    output::answer "⚙️ Setup VIM settings"
    ensure_if_exists_file ~/.vimrc
    ln -s $DOTFILES_PATH/editors/.vimrc ~/.vimrc
    output::write "✅ Done"
  ;;
*)
  exit 1
  ;;
esac