#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/editors/utils/files.sh"

##? Install Visual Studio Code and settings
##?
##? Usage:
##?   vscode extensions
##?   vscode setup
docs::parse "$@"

case $1 in
"extensions")
    if platform::command_exists code; then
        output::answer "🔨 Installing Visual Studio Code extensions"
        EXTENSIONS=(
            codely.codely-theme
            github.github-vscode-theme
            msjsdiag.debugger-for-chrome
            ms-azuretools.vscode-docker
            donjayamanne.githistory
            eamodio.gitlens
            golang.go
            k--kato.intellij-idea-keybindings
            pkief.material-icon-theme
            netcorext.uuid-generator
            redhat.vscode-yaml
            ritwickdey.liveserver
            mikestead.dotenv
            orta.vscode-jest
            rvest.vs-code-prettier-eslint
            quicktype.quicktype
            ms-python.python
            shd101wyy.markdown-preview-enhanced
        )

        for i in ${EXTENSIONS[@]}; do
            code --install-extension $i
        done

        output::write "✅ Done"
    else
        output::error "You haven't got installed code"
    fi
  ;;
  "setup")
    source "$DOTFILES_PATH/scripts/editors/utils/files.sh"
    output::answer "⚙️ Setup Visual Studio Code settings"
    if platform::is_macos; then
        create_if_not_exists_file ~/Library/Application\ Support/Code/User/settings.json
        ensure_if_exists_file ~/Library/Application\ Support/Code/User/settings.json
        cp $DOTFILES_PATH/editors/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
    elif platform::is_linux; then
        create_if_not_exists_file ~/.config/Code/User/settings.json
        ensure_if_exists_file ~/.config/Code/User/settings.json
        cp $DOTFILES_PATH/editors/vscode/settings.json ~/.config/Code/User/settings.json
    elif platform::is_wsl; then
        create_if_not_exists_file $WINHOME/AppData/Roaming/Code/User/settings.json
        ensure_if_exists_file $WINHOME/AppData/Roaming/Code/User/settings.json
        cp $DOTFILES_PATH/editors/vscode/settings.json $WINHOME/AppData/Roaming/Code/User/settings.json
    fi
    output::write "✅ Done"
  ;;
*)
  exit 1
  ;;
esac