#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? ZSH helpers
##?
##? Usage:
##?   zsh optimize
##?   zsh test
##?   zsh reload
##?   zsh clean
docs::parse "$@"

case $1 in
"optimize")
  asl_conf=$(sed 's/notice] store/critical] store/g' /etc/asl.conf)
  sudo sh -c "echo '$asl_conf' > /etc/asl.conf"
  echo "ASL only storing critical files!"

  zsh "$ZIM_HOME/zimfw.zsh" clean-compiled && zsh "$ZIM_HOME/zimfw.zsh" compile

  "$DOTFILES_PATH/bin/dot" shell zsh reload
  ;;
"test")
  script::depends_on hyperfine

  hyperfine '/bin/zsh -i -c exit' --warmup 1

  echo ""
  echo "ZSH INFO:"
  echo "  💻 ZSH       📂 /bin/zsh                    - $(/bin/zsh --version)"

  echo ""
  echo "✨ Currently using $(command -v zsh) ✨"
  ;;
"clean")
  find "$HOME" -name '*.zwc' -delete
  ;;
"reload")
  zsh -i -c "autoload -U compaudit && autoload -Uz compinit && compinit"

  output::empty_line
  output::answer 'Now restart your terminal'
  ;;
*)
  exit 1
  ;;
esac