#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? ZSH helpers
##?
##? Usage:
##?   zsh optimize
##?   zsh test-performance
##?   zsh reload-completions
##?   zsh clean
docs::parse "$@"

case $1 in
"optimize")
  asl_conf=$(sed 's/notice] store/critical] store/g' /etc/asl.conf)
  sudo sh -c "echo '$asl_conf' > /etc/asl.conf"
  echo "ASL only storing critical files!"

  find "$DOTFILES_PATH/shell/zsh" -name '*.zwc' -exec rm -rf {} \;
  find "$DOTFILES_PATH/shell/zsh" -name '*.old' -exec rm -rf {} \;
  find "$DOTFILES_PATH/modules/zimfw" -name '*.zwc' -exec rm -rf {} \;
  find "$DOTFILES_PATH/modules/zimfw" -name '*.old' -exec rm -rf {} \;

  /bin/zsh -c "source ${ZDOTDIR:-${HOME}}/.zlogin"

  "$DOTFILES_PATH/bin/dot" shell zsh reload-completions
  ;;
"test-performance")
  script::depends_on hyperfine

  hyperfine '/bin/zsh -i -c exit' --warmup 1

  echo ""
  echo "ZSH INFO:"
  echo "  💻 ZSH 📂 /bin/zsh              - $(/bin/zsh --version)"
  echo ""
  ;;
"clean")
  find "$HOME" -name '*.zwc' -delete
  ;;
"reload-completions")
  zsh -i -c "autoload -U compaudit && autoload -Uz compinit && compinit"

  output::empty_line
  output::answer 'Now restart your terminal'
  ;;
*)
  exit 1
  ;;
esac