#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Add intellij Code Templates symlink (since it's not synced via JetBrains Toolbox)
#?? 1.0.0
##?
##? Usage:
##?   add_code_templates
docs::parse "$@"

if platform::is_wsl; then
  exit 1;
fi

preferences_dir=""
if platform::is_macos; then
  preferences_dir="$HOME/Library/Application Support/JetBrains"
else
  preferences_dir="$HOME/.config/JetBrains"
fi

intellij_version=$(ls "$preferences_dir" | grep 'IntelliJIdea' | sort -r | head -n 1)

intellij_file_templates_folder="$preferences_dir/$intellij_version/fileTemplates"
rm -rf "$intellij_file_templates_folder"
ln -s -i "$DOTFILES_PATH/editors/intellij/templates/" "$intellij_file_templates_folder"

intellij_code_styles_folder="$preferences_dir/$intellij_version/codestyles"
rm -rf "$intellij_code_styles_folder"
ln -s -i "$DOTFILES_PATH/editors/intellij/styles/" "$intellij_code_styles_folder"

intellij_options_folder="$preferences_dir/$intellij_version/options"
rm -rf "$intellij_options_folder"
ln -s -i "$DOTFILES_PATH/editors/intellij/options/" "$intellij_options_folder"

echo "Applied to path: $intellij_file_templates_folder"
echo "Done for $intellij_version!"

