#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show the public (Default) or private ip
#?? 1.0.0
##?
##? Usage:
##?   ip
##?   ip -p
docs::parse "$@"

if getopts "p" arg; then
  if platform::is_macos; then
    ipconfig getifaddr en0
  else
    hostname -I | cut -d' ' -f1
  fi
else
  dig +short myip.opendns.com @resolver1.opendns.com
fi
