#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install docker
##?
##? Usage:
##?    install
##?

if platform::command_exists docker; then
  if ! platform::command_exists docker-compose; then
    output::error "docker-compose not installed, trying to install"
    if platform::is_linux; then
      COMPOSE_VERSION=`git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oE "[0-9]+\.[0-9][0-9]+\.[0-9]+$" | sort --version-sort | tail -n 1` | log::append "Installing docker-compose"
      sudo sh -c "curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
      sudo chmod +x /usr/local/bin/docker-compose
      sudo sh -c "curl -L https://raw.githubusercontent.com/docker/compose/${COMPOSE_VERSION}/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"
    elif platform::is_macos; then
      output::warning "Docker Desktop for Mac includes Compose along with other Docker apps, so Mac users do not need to install Compose separately."
    elif platform::is_macos_arm; then
      output::warning "Docker Desktop for Mac includes Compose along with other Docker apps, so Mac users do not need to install Compose separately."
    elif platform::is_wsl; then
      output::warning "Docker Desktop for Windows includes Compose along with other Docker apps, so most Windows users do not need to install Compose separately."
    fi
  fi
fi

log::success "Docker Compose installed"
output::write "✅ Docker Compose installed"

