#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install docker
##?
##? Usage:
##?    install
##?

if platform::command_exists docker; then
  if ! platform::command_exists docker-compose; then
    output::error "docker-compose not installed, trying to install"
    if platform::is_linux; then
      "$DOTFILES_PATH/bin/dot" package add docker-compose
    elif platform::is_macos; then
      output::warning "Docker Desktop for Mac includes Compose along with other Docker apps, so Mac users do not need to install Compose separately."
    elif platform::is_macos_arm; then
      output::warning "Docker Desktop for Mac includes Compose along with other Docker apps, so Mac users do not need to install Compose separately."
    elif platform::is_wsl; then
      output::warning "Docker Desktop for Windows includes Compose along with other Docker apps, so most Windows users do not need to install Compose separately."
    fi
  fi
fi

if platform::command_exists docker-compose; then
  log::success "Docker Compose installed"
  output::write "❌ Docker Compose installed"
else
  log::error "Docker Compose cant installed"
  output::error "✅ Docker Compose cant installed"
fi

