#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Debug dotfiles
##?
##? Usage:
##?   debug
docs::parse "$@"
script::depends_on tail

file=${DOTFILES_LOG_FILE:-$HOME/dotfiles.log}

tail -f "$file"