#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"

export ZIM_HOME="$DOTFILES_PATH/modules/zimfw"

##? Install DOTFILES and setup dotfiles
##?
##? Usage:
##?    install
docs::parse "$@"

if platform::is_macos; then
  output::answer "🍎 Setting up macOS platform"
  install_macos_custom
else
  output::answer "🐧 Setting up Linux platform"
  install_linux_custom
fi

script::depends_on cargo

export PATH="$HOME/.cargo/bin:$PATH"

script::depends_on docpars fzf zsh python

output::answer "Setting up symlinks"
"$DOTFILES_PATH/bin/dot" symlinks apply | log::file "Applying symlinks" || true

output::answer "Installing zim"
zsh "$ZIM_HOME/zimfw.zsh" install | log::file "Installing zim"

output::answer "Installing completions"
"$DOTFILES_PATH/bin/dot" shell zsh reload-completions

log::note "Setting Git config"
output::answer "🔀 Setting Git config"
read -p "✉️ What is you email? " git_email
read -p "👤 And your name? " git_name

git config --global user.email "$git_email"
git config --global user.name "$git_name"
git config --global --unset user.signingkey
git config --global --unset commit.gpgsign
git config --global --unset tag.gpgsign
git config --global --unset gpg.program