#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"

export ZIM_HOME="$DOTFILES_PATH/modules/zimfw"

if platform::is_macos; then
  output::write "🍎 Setting up macOS platform"
  install_macos_custom
fi

script::depends_on fzf zsh

##? Install and setup dotfiles
##?
##? Usage:
##?    install

output::write "Setting up symlinks"
"$DOTFILES_PATH/bin/dot" symlinks apply | log::file "Applying symlinks" || true

output::write "Installing zim"
zsh "$ZIM_HOME/zimfw.zsh" install | log::file "Installing zim"

output::write "Installing languages"
"$DOTFILES_PATH/bin/dot" languages install

output::write "Installing completions"
"$DOTFILES_PATH/bin/dot" shell zsh reload_completions
