#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update dotfiles to the latest stable release
##?
##? Usage:
##?    update
docs::parse "$@"

sudo -v

cd "$DOTFILES_PATH"
git stash push git/.gitconfig
git reset --hard >/dev/null 2>&1
git checkout master >/dev/null 2>&1
git pull origin master>/dev/null 2>&1
git stash pop >/dev/null 2>&1

output::answer '✅ dotfiles updated to the latest version'