#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update dotfiles to the latest stable release
##?
##? Usage:
##?    update
docs::parse "$@"

sudo -v

cd "$DOTFILES_PATH"

default_branch = $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

git stash push git/.gitconfig
git reset --hard
git checkout ${default_branch}
git pull origin ${default_branch}
git stash pop

output::answer '✅ dotfiles updated to the latest version'