#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install vim
##?
##? Usage:
##?    install
##?

docs::parse "$@"

if ! platform::command_exists vim; then
  "$DOTFILES_PATH/bin/dot" package add vim
else
  output::write "✔ Vim installed"
fi
