#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install java
##?
##? Usage:
##?    install
##?


if ! platform::command_exists java; then
  if platform::is_macos; then
    "$DOTFILES_PATH/bin/dot" package add openjdk
  elif platform::is_macos_arm; then
    "$DOTFILES_PATH/bin/dot" package add openjdk
  else
    "$DOTFILES_PATH/bin/dot" package add default-jdk
    "$DOTFILES_PATH/bin/dot" package add default-jre
  fi
else
  output::write "✔ Java installed"
fi
